In [25]:
import pandas as pd
url = 'sample_superstore_data.csv'
df = pd.read_csv(url)
df.set_index(['Order ID'], inplace=True)

In [26]:
df.iloc[1]

Row ID                        2
Order Date           01/03/2020
Ship Date            06/03/2020
Ship Mode        Standard Class
Customer ID            CG-12101
Customer Name        Customer 1
Segment                Consumer
Country           United States
City                   New York
State                  New York
Region                     East
Category              Furniture
Sub-Category             Chairs
Sales                   1199.99
Quantity                      5
Discount                   0.15
Profit                   299.99
Name: CA-2020-000002, dtype: object

In [27]:
df.loc['CA-2020-000002']

Row ID                        2
Order Date           01/03/2020
Ship Date            06/03/2020
Ship Mode        Standard Class
Customer ID            CG-12101
Customer Name        Customer 1
Segment                Consumer
Country           United States
City                   New York
State                  New York
Region                     East
Category              Furniture
Sub-Category             Chairs
Sales                   1199.99
Quantity                      5
Discount                   0.15
Profit                   299.99
Name: CA-2020-000002, dtype: object

In [28]:
df.head()

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,
CA-2020-000001,1,01/03/2020,06/03/2020,Standard Class,CG-12100,Customer 0,Consumer,United States,New York,New York,East,Furniture,Chairs,45.98,2,0.00,12.34
CA-2020-000002,2,01/03/2020,06/03/2020,Standard Class,CG-12101,Customer 1,Consumer,United States,New York,New York,East,Furniture,Chairs,1199.99,5,0.15,299.99
CA-2020-000003,3,01/03/2020,06/03/2020,Standard Class,CG-12102,Customer 2,Consumer,United States,New York,New York,East,Furniture,Chairs,56.45,3,0.00,-15.67
CA-2020-000004,4,01/03/2020,06/03/2020,Standard Class,CG-12103,Customer 3,Consumer,United States,New York,New York,East,Furniture,Chairs,899.99,1,0.20,179.99
CA-2020-000005,5,01/03/2020,06/03/2020,Standard Class,CG-12104,Customer 4,Consumer,United States,New York,New York,East,Furniture,Chairs,234.56,4,0.10,58.64

In [29]:
df.loc['CA-2020-000002':'CA-2020-000003'  ,'Ship Mode' :'Segment' ]

                     Ship Mode Customer ID Customer Name   Segment
Order ID
CA-2020-000002  Standard Class    CG-12101    Customer 1  Consumer
CA-2020-000003  Standard Class    CG-12102    Customer 2  Consumer

In [30]:
df.iloc[1:3 , 3:7 ]

                     Ship Mode Customer ID Customer Name   Segment
Order ID
CA-2020-000002  Standard Class    CG-12101    Customer 1  Consumer
CA-2020-000003  Standard Class    CG-12102    Customer 2  Consumer

In [32]:
df.reset_index()

,Order ID,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,CA-2020-000001,1,01/03/2020,06/03/2020,Standard Class,CG-12100,Customer 0,Consumer,United States,New York,New York,East,Furniture,Chairs,45.98,2,0.00,12.34
1,CA-2020-000002,2,01/03/2020,06/03/2020,Standard Class,CG-12101,Customer 1,Consumer,United States,New York,New York,East,Furniture,Chairs,1199.99,5,0.15,299.99
2,CA-2020-000003,3,01/03/2020,06/03/2020,Standard Class,CG-12102,Customer 2,Consumer,United States,New York,New York,East,Furniture,Chairs,56.45,3,0.00,-15.67
3,CA-2020-000004,4,01/03/2020,06/03/2020,Standard Class,CG-12103,Customer 3,Consumer,United States,New York,New York,East,Furniture,Chairs,899.99,1,0.20,179.99
4,CA-2020-000005,5,01/03/2020,06/03/2020,Standard Class,CG-12104,Customer 4,Consumer,United States,New York,New York,East,Furniture,Chairs,234.56,4,0.10,58.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,CA-2020-000096,96,01/03/2020,06/03/2020,First Class,CG-12195,Customer 95,Home Office,United States,Houston,Texas,South,Technology,Accessories,678.90,2,0.00,169.73
96,CA-2020-000097,97,01/03/2020,06/03/2020,First Class,CG-12196,Customer 96,Home Office,United States,Houston,Texas,South,Technology,Accessories,1456.78,6,0.15,364.20
97,CA-2020-000098,98,01/03/2020,06/03/2020,First Class,CG-12197,Customer 97,Home Office,United States,Houston,Texas,South,Technology,Accessories,123.45,3,0.00,30.86
98,CA-2020-000099,99,01/03/2020,06/03/2020,First Class,CG-12198,Customer 98,Home Office,United States,Houston,Texas,South,Technology,Accessories,567.89,2,0.10,141.97
99,CA-2020-000100,100,01/03/2020,06/03/2020,First Class,CG-12199,Customer 99,Home Office,United States,Houston,Texas,South,Technology,Accessories,345.67,4,0.00,86.42